In [2]:
import pandas as pd

reviews = pd.read_csv('steam_reviews.csv')
reviews.head()

,app_id,recommendationid,language,review,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access,timestamp_created
0,730,234359556,koreana,이 게임을 하고 나서 내 자존감이 높아졌다\n인성 터진 개쓰레기들을 만나면서 와 나...,True,165,45,0.939227,0,True,False,False,1788421673
1,730,233465782,english,I thought CS2 was supposed to be a tactical FP...,False,257,47,0.869749,13,True,False,False,1787441343
2,730,233719675,schinese,我爱这个游戏，100%，但很多时候爱不能支撑着我们走下去。\n诚然，我才玩了一千多个小时，对...,False,112,10,0.862449,0,True,False,False,1787719974
3,730,233620085,brazilian,"7.500,00 horas jogadas deve significar algo pa...",True,64,3,0.847348,7,True,False,False,1787603946
4,730,233663687,turkish,yeter artık ota boka güncelleme getirmeyin her...,False,94,17,0.848444,1,True,False,False,1787661449

In [3]:
eng_reviews = reviews[reviews['language'] == 'english']
eng_reviews.head()

,app_id,recommendationid,language,review,voted_up,votes_up,votes_funny,weighted_vote_score,comment_count,steam_purchase,received_for_free,written_during_early_access,timestamp_created
1,730,233465782,english,I thought CS2 was supposed to be a tactical FP...,False,257,47,0.869749,13,True,False,False,1787441343
7,730,234086909,english,cheater's don't even try to hide that they are...,False,102,2,0.834723,13,True,False,False,1788103072
8,730,233905295,english,"Great game, amazing gunplay, but here is a Bro...",True,976,163,0.807245,12,True,False,False,1787926248
9,730,234924603,english,"Yes bro nice game, almost broke my monitor😊😊😊😊...",True,76,51,0.785768,8,True,False,False,1789058855
12,730,234645373,english,DO NOT PLAY THIS GAME - CHEATERS SIMULATOR 2\r...,False,35,1,0.781439,12,True,False,False,1788721972

In [8]:
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer

analyzer = SentimentIntensityAnalyzer()
eng_reviews = eng_reviews.copy()
eng_reviews['review'] = eng_reviews['review'].fillna('').astype(str)
eng_reviews['sentiment_score'] = eng_reviews['review'].apply(
    lambda review: analyzer.polarity_scores(review)['compound']
)

print(eng_reviews[['review', 'sentiment_score']].head())

                                               review  sentiment_score
1   I thought CS2 was supposed to be a tactical FP...           0.9823
7   cheater's don't even try to hide that they are...          -0.6020
8   Great game, amazing gunplay, but here is a Bro...           0.9476
9   Yes bro nice game, almost broke my monitor😊😊😊😊...           0.9981
12  DO NOT PLAY THIS GAME - CHEATERS SIMULATOR 2\r...           0.9803